version: '3.1'

services:

  postgres:
    image: postgres
    restart: ${MAIN_RESTART_POLICY}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_database:/var/lib/postgresql/data
    networks:
      - pet-project-network

  adminer:
    image: adminer
    restart: ${MAIN_RESTART_POLICY}
    ports:
      - ${POSTGRES_ADMINER_EXPOSE_PORT}:8080
    depends_on:
      - "postgres"
    networks:
      - pet-project-network

  goservice:
    image: "goservice:${VERSIONS_GOSERVICE_TAG}"
    depends_on:
      - "postgres"
    networks:
      - pet-project-network

  nginx-angular-go:
    image: "nginx-angular-go:${VERSIONS_NGINX_ANGULAR_GO_TAG}"
    ports:
      - ${NGINX_EXPOSE_PORT_1}:80
      - ${NGINX_EXPOSE_PORT_2}:80
    depends_on:
      - "goservice"
    networks:
      - pet-project-network

volumes:
    postgres_database:
        external: true

networks:
  pet-project-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
